server:
  port : 8082
---
cds:
  odata-v4.endpoint.path: "/"
  datasource:
    csv-paths:
      - "db/data/**"
      - "../db/data/**"
      - "srv/external/data/**"
      - "../srv/external/data/**"

---
spring:
  config.activate.on-profile: default
  datasource:
    url: "jdbc:sqlite:/Users/I553829/Documents/microservice/convert/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  sql:
    init:
      mode: never
